import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import { ThemeProvider } from './components/ThemeProvider';
import CenteredLayout from './components/CenterLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Pyae Phyo Mon',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex-grow">
            <div className="mx-4 m-auto">
              <Header />
            </div>
            <section className="flex gap-4 min-h-[500px]">
              <Sidebar />
              <main className="border-slate-100 px-4">{children}</main>
            </section>
          </div>
          <footer className="text-center py-4 text-slate-400 mt-4 ">
            <small className="text-xs">&copy; Copyright: Pyae Phyo Mon @2025</small>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
